function sendAutomatedReport() {
  const recipientEmail = 'your_email@example.com'; // Replace with a valid email address
  const subject = 'Automated Report';
  const body = 'This is an automated report generated by Google Apps Script.';
  GmailApp.sendEmail(recipientEmail, subject, body);
  Logger.log(`Email sent to ${recipientEmail} with subject '${subject}'.`);
}

function createAutomatedDraft() {
  const recipientEmail = 'your_email@example.com'; // Replace with a valid email address
  const subject = 'Automated Report';
  const body = 'This is an automated report generated by Google Apps Script.';
  GmailApp.createDraft(recipientEmail, subject, body);
  Logger.log(
    `Draft email created for ${recipientEmail} with subject '${subject}'.`
  );
}

function logRecentEmailSubjects() {
  const threads = GmailApp.getInboxThreads(0, 10); // Get the first 10 inbox threads (most recent)
  for (let i = 0; i < threads.length; i++) {
    const messages = threads[i].getMessages();
    if (messages.length > 0) {
      Logger.log(`Subject of recent email ${i + 1}: ${messages.getSubject()}`);
    }
  }
}
